bananapi: enabled watchdog

diff --git a/board/common/overlay/etc/init.d/S02watchdog b/board/common/overlay/etc/init.d/S02watchdog
--- a/board/common/overlay/etc/init.d/S02watchdog
+++ b/board/common/overlay/etc/init.d/S02watchdog
@@ -1,16 +1,18 @@
 #!/bin/sh
-#
-# Start watchdog
-#
+
+test -c /dev/watchdog || exit 0
 
 case "$1" in
     start)
         echo -n "Starting watchdog: "
         watchdog -t 5 /dev/watchdog
-        echo "done"
+        [ $? == 0 ] && echo "done" || echo "failed"
         ;;
 
     stop)
+        echo -n "Stopping watchdog: "
+        kill `pidof watchdog` 2>/dev/null
+        [ $? == 0 ] && echo "done" || echo "failed"
         ;;
 
     restart|reload)
